export const IMAGE_API_KEY = 'cpcaPFtHzyJ6ErMF3s0w48birAUaOF4jCWEVBRCswXe6El7l5DsRKc4p'
export const IMAGE_BASE_URL = 'https://api.pexels.com/v1'
export const WEATHER_API_KEY = 'd0348e617c06556dad4a51a7566a333b'
export const WEATHER_BASE_URL = 'https://api.openweathermap.org/data/2.5/weather'
export const WEATHER_IMG_URL = 'https://openweathermap.org/img/wn'
